[deploy]
startCommand = "php artisan config:clear && php artisan ziggy:generate && php artisan migrate --force && (php artisan schedule:work &) && frankenphp run --config /Caddyfile"
healthcheckPath = "/up"
healthcheckTimeout = 300