/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "dashboard": [],
    "games.index": [],
    "games.create": [],
    "games.store": [],
    "games.show": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.edit": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.update": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.destroy": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.mergeInto": [
        {
            "name": "source",
            "required": true,
            "binding": "id"
        }
    ],
    "games.incrementCopies": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.decrementCopies": [
        {
            "name": "game",
            "required": true,
            "binding": "id"
        }
    ],
    "games.checkDuplicate": [],
    "games.importFromBgg": [],
    "friends.index": [],
    "friends.create": [],
    "friends.store": [],
    "friends.edit": [
        {
            "name": "friend",
            "required": true,
            "binding": "id"
        }
    ],
    "friends.update": [
        {
            "name": "friend",
            "required": true,
            "binding": "id"
        }
    ],
    "friends.destroy": [
        {
            "name": "friend",
            "required": true,
            "binding": "id"
        }
    ],
    "friends.checkDuplicate": [],
    "sessions.index": [],
    "sessions.create": [],
    "sessions.store": [],
    "sessions.show": [
        {
            "name": "session",
            "required": true,
            "binding": "id"
        }
    ],
    "sessions.edit": [
        {
            "name": "session",
            "required": true,
            "binding": "id"
        }
    ],
    "sessions.update": [
        {
            "name": "session",
            "required": true,
            "binding": "id"
        }
    ],
    "sessions.destroy": [
        {
            "name": "session",
            "required": true,
            "binding": "id"
        }
    ],
    "sessions.checkDuplicate": [],
    "sessions.arrange": [
        {
            "name": "session",
            "required": true,
            "binding": "id"
        }
    ],
    "preferences.show": [
        {
            "name": "friend",
            "required": true,
            "binding": "id"
        }
    ],
    "preferences.update": [
        {
            "name": "friend",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "locale.switch": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
